apiVersion: apps/v1
kind: Deployment
metadata:
  name: restoct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restoct
  template:
    metadata:
      labels:
        app: restoct
    spec:
      containers:
        - name: restoct
          image: restoct-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/kbtvuelo?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_ROOT_PASSWORD
